---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
    tier: "{{ .Values.deploy.service.tier }}"
    {{- with .Values.deploy.service.additionalLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres-standard
  type: NodePort
  selector:
    app: "{{ .Release.Name }}"
