name: Docker Build

on:
  release:
    types:
    - created
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set output
        id: vars
        run: |
          EVENT_NAME=${{ github.event_name }}
          if [[ "${EVENT_NAME}" == "release" ]]; then
            REF_NAME=${{ github.ref_name }}
          else
            REF_NAME="pull_request"
          fi
          echo ::set-output name=version::${REF_NAME#v/}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # only push if we are being triggered by a release
          push: ${{ github.event_name == 'release' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pgpool-cloudsql:${{ steps.vars.outputs.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pgpool-cloudsql:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pgpool-cloudsql:buildcache,mode=max
